# Generated by Django 4.2.9 on 2025-06-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_location_remove_employeeprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='location',
            field=models.CharField(choices=[('Jalandhar', 'Jalandhar'), ('Bhogpur', 'Bhogur'), ('Begowal', 'Begowal'), ('Nava_Sehar', 'Nava Sehar')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
