# Generated by Django 4.2.9 on 2025-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeassignment_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
