# Generated by Django 4.2.9 on 2025-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeeassignment_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
