# Generated by Django 4.2.9 on 2026-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontproductimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
