# Generated by Django 4.2.9 on 2026-03-24 12:01

import app.storefront.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_storefrontproductimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefrontproductimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.storefront.models.product_image_upload_to),
        ),
    ]
