# Generated by Django 4.2.9 on 2026-04-16 00:45

import app.storefront.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_storefrontproductreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storefrontproductimage',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='storefrontproductimage',
            name='image',
            field=models.ImageField(default=1, upload_to=app.storefront.models.product_image_upload_to),
            preserve_default=False,
        ),
    ]
