# Generated by Django 4.2.9 on 2024-11-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_profile_alter_auditlog_user_alter_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
