# Generated by Django 4.2.9 on 2026-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
