# Generated by Django 4.2.9 on 2024-11-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_profile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
