# Generated by Django 4.2.9 on 2025-05-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_A',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_B',
        ),
    ]
