# Generated by Django 4.2.9 on 2025-09-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='change_type',
            field=models.CharField(choices=[('PURCHASE_RECEIVE', 'Purchase Receive'), ('SALE', 'Sale'), ('SALE_IN_TRANSIT', 'Sale In Transit'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
    ]
