# Generated by Django 4.2.9 on 2024-11-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_barcode_product_cost_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
