# Generated by Django 4.2.9 on 2025-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_company_product_sku_product_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryimage',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
