# Generated by Django 4.2.9 on 2025-08-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_role_auditlog_tenant_id_inventory_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
