# Generated by Django 4.2.9 on 2024-12-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_location_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PHONE COVER', 'Phone case'), ('SCREEN GUARD', 'Screen guard')], max_length=100),
        ),
    ]
