# Generated by Django 4.2.9 on 2025-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_company_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryimage',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
