# Generated by Django 4.2.9 on 2024-12-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_price_a_product_price_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PHONE COVER', 'Phone cover'), ('SCREEN GUARD', 'Screen guard'), ('AIRPODS', 'Airpods'), ('AIRPOD_CASES', 'Airpod cases'), ('CAMERA_LENS', 'Camera lens'), ('OTHER_ACCESSORIES', 'Other accessories')], max_length=100),
        ),
    ]
