# Generated by Django 4.2.9 on 2025-08-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_category_tenant_id_alter_auditlog_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
