# Generated by Django 4.2.9 on 2025-08-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseorder_vendor_purchaseorderitem_and_more'),
        ('point_of_sale', '0017_invoicenumbersequence_alter_invoice_invoice_number_and_more'),
        ('inventory', '0010_product_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('location', models.CharField(max_length=100)),
                ('change_type', models.CharField(choices=[('PURCHASE_RECEIVE', 'Purchase Receive'), ('SALE', 'Sale'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('quantity_change', models.IntegerField(help_text='Positive for inbound, negative for outbound')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
                ('related_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchase.purchaseorder')),
                ('related_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='point_of_sale.salesorder')),
            ],
            options={
                'db_table': 'stock_movement',
                'ordering': ['-created_at'],
            },
        ),
    ]
