# Generated by Django 4.2.9 on 2024-12-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in Customer'), ('registered', 'Registered Customer')], default='walk_in', max_length=20),
        ),
    ]
