# Generated by Django 4.2.9 on 2024-12-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_debt_customer_total_debt_customerdebt'),
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gpay', 'G-Pay'), ('cheque', 'Cheque')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='unpaid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_debt',
            },
        ),
    ]
