# Generated by Django 4.2.9 on 2025-09-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
