# Generated by Django 4.2.9 on 2024-12-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('point_of_sale', '0002_salesorder_customer_salesorder_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='employee.employeeprofile'),
        ),
    ]
