# Generated by Django 4.2.9 on 2025-07-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0007_delete_customerdebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='location',
            field=models.CharField(default='Main Store', max_length=100),
        ),
    ]
