# Generated by Django 4.2.9 on 2025-07-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0009_remove_invoice_is_paid_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
