# Generated by Django 4.2.9 on 2025-08-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0011_invoice_created_by_invoice_notes_payment_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_term',
        ),
    ]
