# Generated by Django 4.2.9 on 2025-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_remove_payment_due_date_remove_payment_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
