# Generated by Django 4.2.9 on 2025-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0013_invoice_tenant_id_orderitem_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
