# Generated by Django 4.2.9 on 2025-08-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0014_alter_invoice_tenant_id_alter_orderitem_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'permissions': [('view_reports', 'Can view analytics and reports')]},
        ),
    ]
