# Generated by Django 4.2.9 on 2025-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0015_alter_salesorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'order_number_sequence',
            },
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('tenant_id', 'order_number')},
        ),
    ]
