# Generated by Django 4.2.9 on 2024-12-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('customer_type', models.CharField(choices=[('A', 'A - High Priority'), ('B', 'B - Medium Priority'), ('C', 'C - Low Priority')], max_length=1)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('shop', models.CharField(blank=True, max_length=255, null=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
