# Generated by Django 4.2.9 on 2025-08-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customer_name_364ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city'], name='customer_city_27adb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customer_custome_7671c8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['total_debt'], name='customer_total_d_5c3ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant_id', 'name'], name='customer_tenant__523d70_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
