# Generated by Django 4.2.9 on 2025-08-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
