# Generated by Django 4.2.9 on 2025-08-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_walk_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_walk_in',
        ),
    ]
