# Generated by Django 4.2.9 on 2025-07-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerbalance_delete_customerdebt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbalance',
            name='total_balance',
        ),
        migrations.DeleteModel(
            name='CustomerDebt',
        ),
    ]
