# Generated by Django 4.2.9 on 2025-08-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_name_364ac9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_name_364ac9_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_city_27adb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_custome_7671c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_total_d_5c3ed2_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_tenant__523d70_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
