# Generated by Django 4.2.9 on 2025-08-29 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_remove_customer_customer_name_364ac9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('follow_up_date', models.DateField()),
                ('follow_up_type', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('sms', 'SMS'), ('visit', 'Store Visit'), ('social', 'Social Media')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customers.customer')),
            ],
            options={
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('first_order_date', models.DateTimeField(blank=True, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_since_last_order', models.PositiveIntegerField(default=0)),
                ('churn_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('preferred_products', models.JSONField(blank=True, default=list)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
