# Generated by Django 4.2.9 on 2025-07-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customerbalance_total_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalance',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
