# Generated by Django 4.2.9 on 2025-08-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_is_active_customer_last_visit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfollowup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerfollowup',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_visit_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_tier',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_from_sales_order',
            field=models.BooleanField(default=False, help_text='Customer was created during a sales order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_walk_in',
            field=models.BooleanField(default=False, help_text='Indicates if this is a walk-in customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the customer', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (optional for walk-in customers)', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerAnalytics',
        ),
        migrations.DeleteModel(
            name='CustomerFollowUp',
        ),
    ]
