# Generated by Django 4.2.9 on 2025-07-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerbalance_total_balance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerbalance',
            table='customer_balance',
        ),
    ]
