# Generated by Django 4.2.9 on 2025-08-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customerfollowup_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_from_sales_order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_walk_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
