# Generated by Django 4.2.9 on 2025-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customerbalance_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalance',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
