# Generated by Django 4.2.9 on 2025-07-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerbalance_is_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbalance',
            name='is_true',
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='total_balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
