# Generated by Django 4.2.9 on 2025-07-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_customerbalance_is_true_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerBalance',
        ),
    ]
