# Generated by Django 4.2.9 on 2025-08-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customerbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshot', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerBalance',
        ),
    ]
