# Generated by Django 4.2.9 on 2025-08-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customerfinancialsnapshot_customerledger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfinancialsnapshot',
            name='credit_balance',
        ),
    ]
