# Generated by Django 4.2.9 on 2025-08-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_credit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_balance',
        ),
    ]
