# Generated by Django 4.2.9 on 2025-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfinancialsnapshot',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerledger',
            name='tenant_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
