# Generated by Django 4.2.9 on 2025-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerfinancialsnapshot',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerledger',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
