# Generated by Django 4.2.9 on 2025-10-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tenant_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
