# Generated by Django 4.2.9 on 2025-06-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeassignment_location_delete_location'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='employee',
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeeprofile'),
        ),
    ]
