# Generated by Django 4.2.9 on 2025-06-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_bill_description_remove_bill_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='vehicle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
